BookMag/routes/web.php
<?php

use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DescriptionController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\TestController;
use App\Models\Book;
use App\Models\User;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [SiteController::class, 'index'])->name('index');

Route::get('/email', [TestController::class, 'index']);

Route::get('cart', [OrderController::class, 'cart'])->name('cart');

Route::get('add-to-cart/{id}', [OrderController::class, 'addToCart'])->middleware('auth')->name('addToCart');

Route::delete('remove-from-cart', [OrderController::class, 'remove']);

Route::get('/search', [SiteController::class, 'search'])->name('search');

Route::get('/show_category_books/{id}/books', [SiteController::class, 'showCategoryBooks'])->name('site.showCategoryBooks');

Route::get('users/{user}/edit', [RegisteredUserController::class, 'edit'])->name('users.edit');

Route::put('users/{user}', [RegisteredUserController::class, 'update'])->name('users.update');

Route::resource('sites', SiteController::class)->except('index');

Route::get('/dashboard', [DashboardController::class, 'index'])
    ->middleware('auth', 'admin.check')->name('dashboard');

Route::get('users', [RegisteredUserController::class, 'index'])->middleware('auth', 'admin.check')->name('users');

Route::delete('users/{user}', [RegisteredUserController::class, 'destroy'])->middleware('auth')->name('users.destroy');

Route::get('book/{book_id}/description', [DescriptionController::class, 'addDescription'])->name('book.description');

Route::resource('categories', CategoryController::class);

Route::resource('books', BookController::class);

Route::resource('descriptions', DescriptionController::class)->only('index', 'store', 'destroy');

Route::get('book/{id}/reviews', [ReviewController::class, 'book_reviews'])->name('book.reviews');

Route::resource('reviews', ReviewController::class)->only('index', 'store', 'destroy');

Route::get('user/{id}/orders', [OrderController::class, 'user_orders'])->name('user.orders');

Route::resource('orders', OrderController::class);

require __DIR__.'/auth.php';

BookMag/app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function description()
    {
        return $this->hasOne('App\Models\Description');
    }

    public function reviews()
    {
        return $this->hasMany('App\Models\Review');
    }

    public function orders()
    {
        return $this->belongsToMany('App\Models\Order')->withPivot('quantity')->withTimestamps();
    }

}

BookMag/app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Category;
use App\Models\Description;
use App\Models\Review;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class BookController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('show');
        $this->middleware('admin.check')->except('show');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('books/index', ['books' => Book::orderBy('title', 'asc')->paginate(10) ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books/create', ['categories' => Category::orderBy('category_name', 'asc')->get() ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'bail|required|max:200',
            'category_id' => 'bail|required',
            'author' => 'bail|required|max:150',
            'language' => 'bail|required|max:50',
            'size' => 'bail|required|max:50',
            'price' => 'bail|required|max:10',
            'discount' => 'bail|required|max:100',
            'stock' => 'bail|required|max:100',
            'pages' => 'bail|required|max:100',
            'publication' => 'bail|required|max:100',
            'image' => 'bail|required|image'   
        ]);

        $image = $request->file('image');

        $name = time() . '_' . $image->getClientOriginalName();

        $image->storeAs('books/images', $name, 'public');

        $book = new Book;
        $book->title = $request->title;
        $book->category_id = $request->category_id;
        $book->author = $request->author;
        $book->language = $request->language;
        $book->size = $request->size;
        $book->price = $request->price;
        $book->discount = $request->discount;
        $book->stock = $request->stock;
        $book->pages = $request->pages;
        $book->publication = $request->publication;
        $book->image = $name;
        
        $book->save();

        return redirect('books');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        return view('site/showbook', [
            'book' => $book,
            'related_books' => Book::where('category_id', '=', $book->category_id)->orderBy('created_at', 'desc')->limit(3)->get(),
            'reviews' => Review::where('book_id', '=', $book->id)->orderBy('created_at', 'desc')->get()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        return view('books/edit', [
            'book' => $book, 
            'categories' => Category::orderBy('category_name', 'asc')->get()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        $request->validate([
            'title' => 'bail|required|max:200',
            'author' => 'bail|required|max:150',
            'language' => 'bail|required|max:50',
            'size' => 'bail|required|max:50',
            'price' => 'bail|required|max:10',
            'discount' => 'bail|required|max:100',
            'stock' => 'bail|required|max:100',
            'pages' => 'bail|required|max:100',
            'publication' => 'bail|required|max:100',
            'image' => 'bail|image'   
        ]);

        if($request->image){
        $image = $request->file('image');

        $name = time() . '_' . $image->getClientOriginalName();

        $image->storeAs('books/images', $name, 'public');
        $book->image = $name;
        };
        
        $book->title = $request->title;
        $book->category_id = $request->category_id;
        $book->author = $request->author;
        $book->language = $request->language;
        $book->size = $request->size;
        $book->price = $request->price;
        $book->discount = $request->discount;
        $book->stock = $request->stock;
        $book->pages = $request->pages;
        $book->publication = $request->publication;
        
        $book->save();

        return redirect('books');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        DB::transaction(function () use($book) {

            DB::table('descriptions')->where('book_id', '=', $book->id)->delete();

            DB::table('reviews')->where('book_id', '=', $book->id)->delete();

            Storage::disk('public')->delete('\books\images\\' . $book->image);

            $book->delete();
        });
        

        return redirect()->back();
    }
}

BookMag/resources/views/books/create.blade.php
@extends('layouts.admin')

@section('content')

<h3>Adaugă Carte</h3>

            <hr>
            <br />

            @if (1>2)
                <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">×</button> The book was successfully added. 
                </div>
            @endif
            

            <br />

<form action="{{ route('books.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <label>Titlu:</label>
                <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" placeholder="Adaugă titlul cartii" value="{{ old('title') }}">
                @error('title')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>
            <div class="form-group">
                <label>Categorie:</label>
                @if (count($categories) > 0)
                        <select class="form-control" name="category_id">  
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->category_name }}</option>                                                                              
                            @endforeach
                        </select>
                @else
                     <input type="text" placeholder="There is no category" name="category_id" class="form-control @error('category_id') is-invalid @enderror" readonly>
                     @error('category_id')
                    <small class="form-text" style="color: red;">{{ 'First add a category!'  }}</small> 
                    @enderror
                @endif
            </div>

            <div class="form-group">
                <label>Autor:</label>
                <input type="text" name="author" class="form-control @error('author') is-invalid @enderror" placeholder="Adaugă autorul cartii" value="{{ old('author') }}">
                @error('author')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Limba:</label>
                <input type="text" name="language" class="form-control @error('language') is-invalid @enderror" placeholder="Adaugă limba in care este scrisa cartea" value="{{ old('language') }}">
                @error('language')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Dimensiuni:</label>
                <input type="text" name="size" class="form-control @error('size') is-invalid @enderror" placeholder="Exemplu 230 x 200" value="{{ old('size') }}" />
                @error('size')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>
        </div>

        <div class="col-lg-6">
            <div class="form-group">
                <label>Preț:</label>
                <input type="number" name="price" class="form-control @error('price') is-invalid @enderror" placeholder="Adaugă prețul cartii" value="{{ old('price') }}">
                @error('price')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Discount:</label>
                <input type="number" name="discount" class="form-control @error('discount') is-invalid @enderror" placeholder="Adaugă reducerea" value="{{ old('discount') }}">
                @error('discount')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>În stoc:</label>
                <input type="number" name="stock" class="form-control @error('stock') is-invalid @enderror" placeholder="Adaugă numărul de carti în stoc" value="{{ old('stock') }}">
                @error('stock')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Numar pagini:</label>
                <input type="number" name="pages" class="form-control @error('pages') is-invalid @enderror" placeholder="Adaugă numărul de pagini"  value="{{ old('pages') }}"/>
                @error('pages')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Data publicarii:</label>
                <input type="date" name="publication" class="form-control @error('publication') is-invalid @enderror"  value="{{ old('publication') }}"/>
                @error('publication')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <label>Imagine:</label>
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('image') is-invalid @enderror" id="customFile" name="image"  value="{{ old('image') }}">
                @error('image')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            <br /><br />
            <button type="submit" class="btn btn-primary">Adaugă Cartea</button>
            <button type="reset" class="btn btn-danger">Sterge</button>
        </div>
    </div>
</form>

<script>
    $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>

@endsection

BookMag/resources/views/books/edit.blade.php
@extends('layouts.admin')

@section('content')

<h3>Actualizeaza Carte</h3>

            <hr>
            <br />

            @if (1>2)
                <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">×</button> The book was successfully updated. 
                </div>
            @endif
            

            <br />

<form action="{{ route('books.update', ['book'=>$book->id]) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <label>Titlu:</label>
                <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" placeholder="Adaugă titlul cartii" value="{{ $book->title }}">
                @error('title')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>
            <div class="form-group">
                <label>Categorie:</label>
                @if (count($categories) > 0)
                        <select class="form-control" name="category_id">  
                            @foreach ($categories as $category)
                            <option value="{{ $category->id }}" {{ $category->id == $book->category->id ? 'selected' : null }}>{{ $category->category_name }}</option>                                                                              
                            @endforeach
                        </select>
                     @else
                     <input type="text" value="There is no category" name="category_id" class="form-control" readonly>
                @endif
            </div>

            <div class="form-group">
                <label>Autor:</label>
                <input type="text" name="author" class="form-control @error('author') is-invalid @enderror" placeholder="Adaugă autorul cartii" value="{{ $book->author }}">
                @error('author')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Limba:</label>
                <input type="text" name="language" class="form-control @error('language') is-invalid @enderror" placeholder="Adaugă limba in care este scrisa cartea" value="{{ $book->language }}">
                @error('language')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Dimensiuni:</label>
                <input type="text" name="size" class="form-control @error('size') is-invalid @enderror" placeholder="Exemplu 230 x 200" value="{{ $book->size }}" />
                @error('size')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>
        </div>

        <div class="col-lg-6">
            <div class="form-group">
                <label>Preț:</label>
                <input type="number" name="price" class="form-control @error('price') is-invalid @enderror" placeholder="Adaugă prețul cartii" value="{{ $book->price }}">
                @error('price')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Discount:</label>
                <input type="number" name="discount" class="form-control @error('discount') is-invalid @enderror" placeholder="Adaugă reducerea" value="{{ $book->discount }}">
                @error('discount')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>În stoc:</label>
                <input type="number" name="stock" class="form-control @error('stock') is-invalid @enderror" placeholder="Adaugă numărul de carti în stoc" value="{{ $book->stock }}">
                @error('stock')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Numar pagini:</label>
                <input type="number" name="pages" class="form-control @error('pages') is-invalid @enderror" placeholder="Adaugă numărul de pagini"  value="{{ $book->pages }}"/>
                @error('pages')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>

            <div class="form-group">
                <label>Data publicarii:</label>
                <input type="date" name="publication" class="form-control @error('publication') is-invalid @enderror"  value="{{ $book->publication }}"/>
                @error('publication')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <label>Imagine:</label>
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('image') is-invalid @enderror" id="customFile" name="image"  value="{{ $book->image }}">
                @error('image')
                    <small class="form-text" style="color: red;">{{ $message  }}</small> 
                @enderror
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            <br /><br />
            <button type="submit" class="btn btn-primary">Actualizeaza Cartea</button>
            <button type="reset" class="btn btn-danger">Sterge</button>
        </div>
    </div>
</form>

<script>
    $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>

@endsection

BookMag/resources/views/books/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-lg-12">

        <a href="{{ route('books.create') }}" class="btn btn-primary">Adaugă carte noua</a>

        <br /><br />
        <div class="table-responsive-lg">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Titlu</th>
                        <th>Categorie</th>
                        <th>Author</th>
                        <th>Preț</th>
                        <th>Pagini</th>
                        <th>Publicare</th>
                        <th>Limba</th>
                        <th>Dimensiuni</th>
                        <th>Stoc</th>
                        <th>Reviews</th>
                        <th>Acțiuni</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($books as $book)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $book->title }}</td>
                            <td>{{ $book->category->category_name }}</td>
                            <td>{{ $book->author }}</td>
                            <td>{{ $book->price }}</td>
                            <td>{{ $book->pages }}</td>
                            <td>{{ date('Y', strtotime($book->publication)) }}</td>
                            <td>{{ $book->language }}</td>
                            <td>{{ $book->size }}</td>
                            <td>{{ $book->stock }}</td>
                            <td><a href="{{ route('book.reviews', ['id'=>$book->id]) }}">{{ $book->reviews()->count() }}</a></td>
                            <td>
                                <a href="{{ route('books.show', ['book'=>$book->id ]) }}" target="_blank"><i class="fas fa-eye text-success"></i></a> &nbsp;
                                <a href="{{ route('books.edit', ['book'=>$book->id ]) }}"><i class="fas fa-pencil-alt text-primary"></i></a> &nbsp;
                                <a href="{{ route('book.description', ['book_id'=>$book->id ]) }}"><i class="fas fa-file-alt text-primary"></i></a> &nbsp;
                                <a onclick="event.preventDefault(); document.getElementById('book-delete-{{ $book->id }}').submit();" href="{{ route('books.destroy', ['book'=>$book->id ]) }}"><i class="fas fa-trash-alt text-danger"></i></a>
                                <form action="{{ route('books.destroy', ['book'=>$book->id ]) }}" method="POST" id="book-delete-{{ $book->id }}">
                                    @csrf
                                    @method('DELETE')
                            </form>
                            </td>
                        </tr>
                    @endforeach
                   
                </tbody>
            </table>
        </div>

        <hr>

      
        <ul class="pagination justify-content-center">
            <li>{{ $books->links() }}</li>
        </ul>

    </div>
</div>

@endsection