BookMag/routes/web.php
<?php

use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DescriptionController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\TestController;
use App\Models\Book;
use App\Models\User;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [SiteController::class, 'index'])->name('index');

Route::get('/email', [TestController::class, 'index']);

Route::get('cart', [OrderController::class, 'cart'])->name('cart');

Route::get('add-to-cart/{id}', [OrderController::class, 'addToCart'])->middleware('auth')->name('addToCart');

Route::delete('remove-from-cart', [OrderController::class, 'remove']);

Route::get('/search', [SiteController::class, 'search'])->name('search');

Route::get('/show_category_books/{id}/books', [SiteController::class, 'showCategoryBooks'])->name('site.showCategoryBooks');

Route::get('users/{user}/edit', [RegisteredUserController::class, 'edit'])->name('users.edit');

Route::put('users/{user}', [RegisteredUserController::class, 'update'])->name('users.update');

Route::resource('sites', SiteController::class)->except('index');

Route::get('/dashboard', [DashboardController::class, 'index'])
    ->middleware('auth', 'admin.check')->name('dashboard');

Route::get('users', [RegisteredUserController::class, 'index'])->middleware('auth', 'admin.check')->name('users');

Route::delete('users/{user}', [RegisteredUserController::class, 'destroy'])->middleware('auth')->name('users.destroy');

Route::get('book/{book_id}/description', [DescriptionController::class, 'addDescription'])->name('book.description');

Route::resource('categories', CategoryController::class);

Route::resource('books', BookController::class);

Route::resource('descriptions', DescriptionController::class)->only('index', 'store', 'destroy');

Route::get('book/{id}/reviews', [ReviewController::class, 'book_reviews'])->name('book.reviews');

Route::resource('reviews', ReviewController::class)->only('index', 'store', 'destroy');

Route::get('user/{id}/orders', [OrderController::class, 'user_orders'])->name('user.orders');

Route::resource('orders', OrderController::class);

require __DIR__.'/auth.php';

BookMag/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function books()
    {
        return $this->hasMany('App\Models\Book');
    }
}

BookMag/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
    $this->middleware('auth');
    $this->middleware('admin.check');
    }

    public function index()
    {
        return view('categories/index', [
            'categories' => Category::orderBy('category_name', 'asc')->paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'category_name' => 'bail|required|max:50'
        ]);

        $category = new Category;
        $category->category_name = $request->category_name;
        $category->save();

        return redirect('categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories/edit', [
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'category_name' => 'bail|required|max:50'
        ]);

        $category->category_name = $request->category_name;
        $category->save();

        return redirect('categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->back();
    }
}

BookMag/resources/views/categories/create.blade.php
@extends('layouts.admin')

@section('content')
    
    <form action="{{ route('categories.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">

                <h3>Adaugă Categorie</h3>
                <hr>
                <br>

                <div class="form-group">
                    <label>Nume:</label>
                    <input type="text" name="category_name" class="form-control @error('category_name') is-invalid @enderror" placeholder="Adaugă numele categoriei" />
                    @error('category_name')
                            <small class="form-text" style="color: red;">{{ $message  }}</small> 
                    @enderror
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Adaugă Categoria</button>

            </div>
            <div class="col-lg-2"></div>
        </div>
    </form>

@endsection

BookMag/resources/views/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
    
    <form action="{{ route('categories.update', ['category'=>$category->id]) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">

                <h3>Actualizeaza Categorie</h3>
                <hr>
                <br>

                <div class="form-group">
                    <label>Nume:</label>
                    <input type="text" name="category_name" class="form-control @error('category_name') is-invalid @enderror" value="{{ $category->category_name }}" />
                    @error('category_name')
                            <small class="form-text" style="color: red;">{{ $message  }}</small> 
                    @enderror
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Actualizeaza Categoria</button>

            </div>
            <div class="col-lg-2"></div>
        </div>
    </form>

@endsection

BookMag/resources/views/categories/index.blade.php
@extends('layouts.admin')

@section('content')
    
<div class="row">
    <div class="col-lg-12">

        <a href="{{ route('categories.create') }}" class="btn btn-primary">Adaugă categorie noua</a>

        <br /><br />

        <div class="table-responsive-sm">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Categorie</th>
                        <th>Carti</th>
                        <th>În stoc</th>
                        <th>Acțiuni</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($categories as $category)
                        <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $category->category_name }}</td>
                        <td>{{ $category->books()->count() }}</td>
                        <td>36</td>
                        <td>
                            <a href="{{ route('categories.edit', ['category'=>$category->id ]) }}"><i class="fas fa-pencil-alt text-primary"></i></a> &nbsp;
                            <a onclick="event.preventDefault(); document.getElementById('category-delete-{{ $category->id }}').submit();" href="{{ route('categories.destroy', ['category'=>$category->id ]) }}"><i class="fas fa-trash-alt text-danger"></i></a>
                                <form action="{{ route('categories.destroy', ['category'=>$category->id ]) }}" method="POST" id="category-delete-{{ $category->id }}">
                                    @csrf
                                    @method('DELETE')
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    
                </tbody>
            </table>
        </div>

        <hr>

        <ul class="pagination justify-content-center">
            <li>{{ $categories->links() }}</li>
        </ul>

    </div>
</div>

@endsection