BookMag/routes/web.php
<?php

use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DescriptionController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\TestController;
use App\Models\Book;
use App\Models\User;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [SiteController::class, 'index'])->name('index');

Route::get('/email', [TestController::class, 'index']);

Route::get('cart', [OrderController::class, 'cart'])->name('cart');

Route::get('add-to-cart/{id}', [OrderController::class, 'addToCart'])->middleware('auth')->name('addToCart');

Route::delete('remove-from-cart', [OrderController::class, 'remove']);

Route::get('/search', [SiteController::class, 'search'])->name('search');

Route::get('/show_category_books/{id}/books', [SiteController::class, 'showCategoryBooks'])->name('site.showCategoryBooks');

Route::get('users/{user}/edit', [RegisteredUserController::class, 'edit'])->name('users.edit');

Route::put('users/{user}', [RegisteredUserController::class, 'update'])->name('users.update');

Route::resource('sites', SiteController::class)->except('index');

Route::get('/dashboard', [DashboardController::class, 'index'])
    ->middleware('auth', 'admin.check')->name('dashboard');

Route::get('users', [RegisteredUserController::class, 'index'])->middleware('auth', 'admin.check')->name('users');

Route::delete('users/{user}', [RegisteredUserController::class, 'destroy'])->middleware('auth')->name('users.destroy');

Route::get('book/{book_id}/description', [DescriptionController::class, 'addDescription'])->name('book.description');

Route::resource('categories', CategoryController::class);

Route::resource('books', BookController::class);

Route::resource('descriptions', DescriptionController::class)->only('index', 'store', 'destroy');

Route::get('book/{id}/reviews', [ReviewController::class, 'book_reviews'])->name('book.reviews');

Route::resource('reviews', ReviewController::class)->only('index', 'store', 'destroy');

Route::get('user/{id}/orders', [OrderController::class, 'user_orders'])->name('user.orders');

Route::resource('orders', OrderController::class);

require __DIR__.'/auth.php';

BookMag/resources/views/cart.blade.php
@extends('layouts.site')

@section('content')

<div class="col-lg-12">

    <br /><br />

    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">

<?php $total = 0; $totalbooks = 0; ?>
@if(session('cart'))

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nr.</th>
                                <th>Carte</th>
                                <th>Pret Carte</th>
                                <th>Cantitate</th>
                                <th>Pret Total</th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>


    @foreach(session('cart') as $id => $details)
        <?php $total += $details['price'] * $details['quantity']; $totalbooks += $details['quantity']; ?>
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $details['title'] }}</td>
            <td>{{ $details['price'] }} lei</td>
            <td data-th="Quantity">{{ $details['quantity'] }}</td>
            <td data-th="Subtotal" class="text-center">{{ $details['price'] * $details['quantity'] }} lei</td>      
            <td><button class="btn btn-danger btn-sm remove-from-cart" data-id="{{ $id }}">sterge</button></td>
        </tr>
    @endforeach

@else No books added yet.

@endif

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>Numar Produse</dt>
                        <dd>{{ $totalbooks}}</dd>
                        <dt>Pret Total</dt>
                        <dd>{{ $total }}</dd>
                    </dl>
                    <hr>

                    <form action="{{ route('orders.store') }}" method="POST">
                        @csrf
                        <button type="submit" class="btn btn-primary btn-block">Plaseaza Comanda</button>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <br />

    <!-- start card alte oferte -->
    <div class="card">
        <div class="card-header">Alte oferte</div>
        <div class="card-body">
            <div class="row">

                @foreach ($recommended_books as $item)
                    <div class="col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="{{ asset('storage/books/images/' . $item->image) }}" style="object-fit: cover;" height="200px">
                        <div class="card-body" style="text-align: center;">
                            <h5 class="card-title">{{ $item->title }}, {{ $item->author }}</h5>
                            <p class="card-text" style="color: red;">
                                <b>{{ $item->price }}</b><sup>00</sup> Lei
                            </p>
                            <a href="{{ route('books.show', ['book'=>$item->id ]) }}" class="btn btn-primary btn-block">Vezi detalii</a>
                        </div>
                    </div>
                    </div>
                @endforeach
                
            </div>
        </div>
    </div>
    <!-- end card alte oferte -->

</div>

<script type="text/javascript">
        $(".remove-from-cart").click(function (e) {
            e.preventDefault();
            var ele = $(this);
            if(confirm("Are you sure?")) {
                $.ajax({
                    url: '{{ url('remove-from-cart') }}',
                    method: "DELETE",
                    data: {_token: '{{ csrf_token() }}', id: ele.attr("data-id")},
                    success: function (response) {
                        window.location.reload();
                    }
                });
            }
        });
</script>
    
@endsection

BookMag/resources/views/dashboard.blade.php
@extends('layouts/admin')


@section('content')   
    
<div class="row">

    <div class="col-lg-12">
        <h4 class="border border-top-0 border-left-0 border-right-0">Statisticile zilei curente</h4>
        <br />
        <div class="row">
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $today_books }}</dt>
                            <dd>Total Carti Vandute</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $today_orders }}</dt>
                            <dd>Total Comenzi</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $today_income }}</dt>
                            <dd>Total Incasari</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <br /><br />
        <h4 class="border border-top-0 border-left-0 border-right-0">Situatie vanzari/incasari</h4>
        <br />
        <div class="row">
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $total_books }}</dt>
                            <dd>Total Carti Vandute</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $orders }}</dt>
                            <dd>Total Comenzi</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $total_income }}</dt>
                            <dd>Total Incasari</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <br /><br />
        <h4 class="border border-top-0 border-left-0 border-right-0">Alte detalii</h4>
        <br />
        <div class="row">
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $books }}</dt>
                            <dd>Total Carti</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $books_with_discount }}</dt>
                            <dd>Carti cu Discount</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-light text-dark shadow-sm">
                    <div class="card-body">
                        <dl style="margin: 0px;">
                            <dt>{{ $users }}</dt>
                            <dd>Utilizatori</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


@endsection

BookMag/resources/views/description-create.blade.php
@extends('layouts.admin')

@section('content')

<h3>Descriere: {{ $book->title }}</h3>

            <hr>
            <br />

<form action="{{ route('descriptions.store') }}" method="POST">
    @csrf
    <div class="row">
        <div class="col-lg-12">
            <input type="hidden" name="book_id" value="{{ $book->id }}">
            <div class="form-group">
                <textarea class="form-control @error('description') is-invalid @enderror" placeholder="Adaugă descrierea produsului" 
                rows="12" name="description">@if (!empty($book->description)) {{ $book->description->text }}@endif</textarea>
                @error('description')
                    <small class="form-text" style="color: red;">{{ $message  }}</small>                    
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Adaugă Descrierea</button>
            <button type="reset" class="btn btn-danger">Sterge</button>
        </div>
    </div>
</form>
    
@endsection

BookMag/resources/views/orders.blade.php
@extends('layouts.admin')

@section('content')
    
        <!-- start main content -->
        <div class="row">

            <div class="col-lg-12">
 
                <h2>Toate comenzile</h2>

                <div class="row"> 
                    
                    @foreach ($orders as $order)

                    <div class="col-md-4">
                        
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Numar carti <span style="float: right; font-weight: bolder;"><a href="#" data-toggle="modal" data-target="#modal-detalii-1">{{ $order->books()->count() }}</a></span></h5>
                                <h5 class="card-title">Pret total <span style="float: right; font-weight: bolder;">{{ $order->total_price }}</span></h5>
                                <h5 class="card-title">Data <span style="float: right; font-weight: bolder;">{{ $order->created_at }}</span></h5>
                                <h5 class="card-title">Client <span style="float: right; font-weight: bolder;"><a href="{{ route('user.orders', ['id'=>$order->user->id]) }}">{{ $order->user->name }}</a></span></h5>
                                <hr>
                                <h5 class="card-title">Adresa de livrare</h5>
                                <p class="card-text">{{ $order->user->address }}</p>
                                <hr>
                                @if ($order->status == 'pending')
                                        <h6 class="card-title">Status <span style="float: right; color:brown;">{{ $order->status }}</span></h6>
                                   @else
                                        <h6 class="card-title">Status <span style="float: right; color:rgba(4, 185, 4, 0.884);">{{ $order->status }}</span></h6>
                                @endif
                                <hr>
                                <a href="{{ route('orders.show', ['order'=>$order->id ]) }}" class="card-link">Finalizeaza</a>
                                <a onclick="event.preventDefault(); document.getElementById('order-delete-{{ $order->id }}').submit();" href="{{ route('orders.destroy', ['order'=>$order->id ]) }}" class="card-link" style="float: right;">Sterge</a>
                                <form action="{{ route('orders.destroy', ['order'=>$order->id ]) }}" method="POST" id="order-delete-{{ $order->id }}">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </div>
                        </div>
                        <div class="modal" id="modal-detalii-1">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    
                                    <div class="modal-body">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Nr.</th>
                                                    <th>Carte</th>
                                                    <th>Pret Carte</th>
                                                    <th>Cantitate</th>
                                                    <th>Pret Total</th>
                                                </tr>
                                            </thead>
                                            <tbody>

                                                @foreach ($order->books as $item)
                                                  <tr>
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td>{{ $item->title }}</td>
                                                    <td>{{ $item->price }}</td>
                                                    <td>{{ $item->pivot->quantity }}</td>
                                                    <td>{{ $item->price * $item->pivot->quantity }}</td>
                                                </tr>  
    
                                                @endforeach
                                                
                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                @endforeach

                   
                    


                </div>
            </div>
                {{ $orders->links() }}
        </div>

@endsection

BookMag/resources/views/orders_by_user.blade.php
@extends('layouts.admin')

@section('content')
    
        <!-- start main content -->
        <div class="row">

            <div class="col-lg-12">
              <!--  <h4 class="border border-top-0 border-left-0 border-right-0">
                    <a href="">Comenzi in asteptare</a>
                    <a href="" style="float: right;">Istoric comenzi</a>
                </h4>
                
                <br /><br /> -->
                <h2>Comenzile unui client</h2>

                <div class="row"> 
                    
                    @foreach ($orders as $order)

                    <div class="col-md-4">
                        
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Numar carti <span style="float: right; font-weight: bolder;"><a href="#" data-toggle="modal" data-target="#modal-detalii-1">{{ $order->books()->count() }}</a></span></h5>
                                <h5 class="card-title">Pret total <span style="float: right; font-weight: bolder;">{{ $order->total_price }}</span></h5>
                                <h5 class="card-title">Data <span style="float: right; font-weight: bolder;">{{ $order->created_at }}</span></h5>
                                <h5 class="card-title">Client <span style="float: right; font-weight: bolder;"><a href="{{ route('users.edit', ['user'=>$order->user->id ]) }}">{{ $order->user->name }}</a></span></h5>
                                <hr>
                                <h5 class="card-title">Adresa de livrare</h5>
                                <p class="card-text">{{ $order->user->address }}</p>
                                <hr>
                                @if ($order->status == 'pending')
                                        <h6 class="card-title">Status <span style="float: right; color:brown;">{{ $order->status }}</span></h6>
                                   @else
                                        <h6 class="card-title">Status <span style="float: right; color:rgba(4, 185, 4, 0.884);">{{ $order->status }}</span></h6>
                                @endif
                                <hr>
                                <a href="{{ route('orders.show', ['order'=>$order->id ]) }}" class="card-link">Finalizeaza</a>
                                <a onclick="event.preventDefault(); document.getElementById('order-delete-{{ $order->id }}').submit();" href="{{ route('orders.destroy', ['order'=>$order->id ]) }}" class="card-link" style="float: right;">Sterge</a>
                                <form action="{{ route('orders.destroy', ['order'=>$order->id ]) }}" method="POST" id="order-delete-{{ $order->id }}">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </div>
                        </div>
                        <div class="modal" id="modal-detalii-1">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    
                                    <div class="modal-body">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Nr.</th>
                                                    <th>Carte</th>
                                                    <th>Pret Carte</th>
                                                    <th>Cantitate</th>
                                                    <th>Pret Total</th>
                                                </tr>
                                            </thead>
                                            <tbody>

                                                @foreach ($order->books as $item)
                                                  <tr>
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td>{{ $item->title }}</td>
                                                    <td>{{ $item->price }}</td>
                                                    <td>{{ $item->pivot->quantity }}</td>
                                                    <td>{{ $item->price * $item->pivot->quantity }}</td>
                                                </tr>  
    
                                                @endforeach
                                                
                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                @endforeach

                   
                    


                </div>
            </div>
                {{ $orders->links() }}
        </div>

@endsection

BookMag/resources/views/reviews.blade.php
@extends('layouts.admin')

@section('content')
    
<div class="row">
                
    <div class="col-lg-12">
        
        <div class="table-responsive-sm">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Carte</th>
                        <th>Nume</th>
                        <th>Mesaj</th>
                        <th>Rating</th>
                        <th>Data</th>
                        <th>Acțiuni</th>
                    </tr>
                </thead>
                <tbody>

 
                        @foreach ($reviews as $review)
                        <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $review->book->title }}</td>
                        <td>{{ $review->name }}</td>
                        <td>{{ $review->text }}</td>
                        <td>{{ $review->rating }}★</td>
                        <td>{{ $review->created_at }}</td>
                        <td>
                            <a onclick="event.preventDefault(); document.getElementById('review-delete-{{ $review->id }}').submit();" href="{{ route('reviews.destroy', ['review'=>$review->id ]) }}"><i class="fas fa-trash-alt text-danger"></i></a>
                                <form action="{{ route('reviews.destroy', ['review'=>$review->id ]) }}" method="POST" id="review-delete-{{ $review->id }}">
                                    @csrf
                                    @method('DELETE')
                            </form>
                        </td>
                    </tr>
                    @endforeach

                    

                </tbody>
            </table>
        </div>

        <hr>

        <ul class="pagination justify-content-center">
           <li>{{ $reviews->links() }}</li>
        </ul>

    </div>
</div>

@endsection

BookMag/resources/views/reviews_by_book.blade.php
@extends('layouts.admin')

@section('content')
    
<div class="row">
                
    <div class="col-lg-12">
        
        <div class="table-responsive-sm">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Carte</th>
                        <th>Nume</th>
                        <th>Mesaj</th>
                        <th>Rating</th>
                        <th>Data</th>
                        <th>Acțiuni</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($reviews as $review)
                        <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $review->book->title }}</td>
                        <td>{{ $review->name }}</td>
                        <td>{{ $review->text }}</td>
                        <td>{{ $review->rating }}★</td>
                        <td>{{ $review->created_at }}</td>
                        <td>
                            <a onclick="event.preventDefault(); document.getElementById('review-delete-{{ $review->id }}').submit();" href="{{ route('reviews.destroy', ['review'=>$review->id ]) }}"><i class="fas fa-trash-alt text-danger"></i></a>
                                <form action="{{ route('reviews.destroy', ['review'=>$review->id ]) }}" method="POST" id="review-delete-{{ $review->id }}">
                                    @csrf
                                    @method('DELETE')
                            </form>
                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>

        <hr>


    </div>
</div>

@endsection