LaraBlog/routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\SubscriberController;
use App\Http\Middleware\LogHistory;
use Illuminate\Support\Facades\Redis;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FeedController::class, 'index']);

Route::get('/search', [FeedController::class, 'search'])->name('search');

Route::get('/show_category_posts/{id}/articles', [FeedController::class, 'showCategoryPosts'])->name('feed.showCategoryPosts');

Route::get('/dashboard', [DashboardController::class, 'index']);

Route::get('/categories/{id}/articles', [CategoryController::class, 'showArticlesByCategory'])->name('categories.showArticlesByCategory');

Route::get('/articles/{id}/comments', [CommentController::class, 'article_comments'])->name('comments.article_comments');

Route::resources([
    'articles' => ArticleController::class,
    'categories' => CategoryController::class,
    'comments' => CommentController::class,
    'subscribers' => SubscriberController::class,
    'history' => HistoryController::class, 
    ]);

LaraBlog/app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }
}

LaraBlog/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Middleware\BlogHistory;
use App\Models\Article;
use App\Models\Category;
use App\Models\Comment;
use Illuminate\Http\Request;

class ArticleController extends Controller
{

    public function __construct()
    {
        $this->middleware('count.views')->only('show');
        $this->middleware('blog.history')->only('show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('articles/index', [
            'articles' => Article::orderBy('created_at', 'desc')->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles/create', [
            'categories' => Category::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'bail|required|max:100',
            'content' => 'bail|required|max:10000'
        ]);

        $article = new Article;
        $article->category_id = $request->category_id;
        $article->title = $request->title;
        $article->content = strip_tags($request->content);
        $article->save();

        return redirect('/articles');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */

    

    public function show(Article $article)
    {
        return view('post', [
            'article' => $article,
            'related_articles' => Article::where('category_id', '=', $article->category_id)->orderBy('created_at', 'desc')->limit(3)->get(),
            'latest_articles' => Article::latest()->limit(3)->get(),
            'categories' => Category::all()->split(2),
            'comments' => Comment::orderBy('created_at', 'desc')->get()
        ]);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('articles/edit', [
            'article' => $article,
            'categories' => Category::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $request->validate([
            'title' => 'bail|required|max:100',
            'content' => 'bail|required|max:10000'
        ]);

        $article->category_id = $request->category_id;
        $article->title = $request->title;
        $article->content = strip_tags($request->content);
        $article->save();

        return redirect('/articles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();

        return redirect()->back();
    }
}

LaraBlog/resources/views/articles/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Create Article</title>
    
   @include('shared.meta_header')

</head>

<body>

<!-- Navigation menu -->
@include('shared.navmenu')

<!-- Admin header -->
@include('shared.admin_header')

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">
            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">

                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Create Article</h5>
                                        </div>
                                        <div class="card-block">
                                        <form action="{{ route('articles.store') }}" method="POST">
                                            
                                            @method('POST')

                                            @csrf

                                                <div class="row mb-3">
                                                    <div class="col-sm-6 col-xl-9">
                                                        <div class="form-group">

                                                            <label>Categories</label>

                                                            @if (count($categories) > 0)
                                                               <select class="form-control" name="category_id">  
                                                                    @foreach ($categories as $category)
                                                                
                                                               <option value="{{ $category->id }}">{{ $category->category_name }}</option>
                                                                                                                                    
                                                                    @endforeach
                                                                </select>
                                                            @else
                                                                <input type="text" value="There is no category" name="category_id" class="form-control" readonly>
                                                            @endif

                                                            
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6 col-xl-3">
                                                    <button {{ count($categories) ? null : 'disabled' }} class="btn btn-primary shadow-1 text-uppercase btn-block" style="margin-top: 28px;" type="submit">Save article</button>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label>Article Title</label>
                                                    <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" >
                                                    @error('title')
                                                <small class="form-text" style="color: red;">{{ $message }}</small>
                                                    @enderror
                                                </div>

                                                <br />
                                                
                                                <textarea name="content" id="tinymce-editor" class="form-control @error('content') is-invalid @enderror"></textarea>
                                                    @error('content')
                                                <small class="form-text" style="color: red;">{{ $message }}</small>
                                                    @enderror
                                            </form>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- [ Main Content ] end -->

    @include('shared.scripts')

    <!-- tinymce editor -->
    <script src="{{ asset('admin/plugins/tinymce/tinymce.min.js') }}"></script>

    <script type="text/javascript">
        // tinymce editor
        $(window).on('load', function() {
            tinymce.init({
                selector: '#tinymce-editor',
                height: 600,
                theme: 'modern',
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
                ],
                toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
                image_advtab: true
            });
        });
    </script>

</body>

</html>

LaraBlog/resources/views/articles/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Update article</title>
    
    @include('shared.meta_header')

</head>

<body>

   <!-- Navigation menu -->
@include('shared.navmenu')


<!-- Admin header -->
@include('shared.admin_header')



    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">
            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">

                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Update Article</h5>
                                        </div>
                                        <div class="card-block">

                                        <form action="{{ route('articles.update', ['article'=>$article->id]) }}" method="POST">

                                            @csrf
                                            @method('PUT')

                                                <div class="row mb-3">
                                                    <div class="col-sm-6 col-xl-9">
                                                        <div class="form-group">
                                                            <label>Categories</label>
                                                            @if (count($categories) > 0)
                                                               <select class="form-control" name="category_id">  
                                                                    @foreach ($categories as $category)
                                                                
                                                               <option value="{{ $category->id }}" {{ $category->id == $article->category->id ? 'selected' : null }}>{{ $category->category_name }}</option>
                                                                                                                                    
                                                                    @endforeach
                                                                </select>
                                                            @else
                                                                <input type="text" value="There is no category" name="category_id" class="form-control" readonly>
                                                            @endif
                                                            
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6 col-xl-3">
                                                        <button class="btn btn-primary shadow-1 text-uppercase btn-block" style="margin-top: 28px;" type="submit">update article</button>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                <label>Article title</label>
                                                    <input type="text" value="{{ $article->title }}" class="form-control @error('title') is-invalid @enderror" name="title">
                                                    @error('title')
                                                <small class="form-text" style="color: red;">{{ $message }}</small>
                                                    @enderror
                                                </div>

                                                <br />
                                                
                                                <textarea name="content" class="form-control @error('content') is-invalid @enderror" id="tinymce-editor">{{ $article->content }}</textarea>
                                                @error('content')
                                                <small class="form-text" style="color: red;">{{ $message }}</small>
                                                    @enderror
                                            </form>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- [ Main Content ] end -->

    @include('shared.scripts')

    <!-- tinymce editor -->
    <script src="{{ asset('admin/plugins/tinymce/tinymce.min.js') }}"></script>

    <script type="text/javascript">
        // tinymce editor
        $(window).on('load', function() {
            tinymce.init({
                selector: '#tinymce-editor',
                height: 600,
                theme: 'modern',
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
                ],
                toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
                image_advtab: true
            });
        });
    </script>

</body>

</html>

LaraBlog/resources/views/articles/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Articles</title>
    
    @include('shared.meta_header')
  

</head>

<body>

    <!-- Navigation menu -->
@include('shared.navmenu')

<!-- Admin header -->
@include('shared.admin_header')


    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">
            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">

                                <div class="col-lg-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Articles</h5>
                                        </div>
                                        <div class="card-body">
                                            <div class="table-responsive">
                                                <table class="table table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>#</th>
                                                            <th>Article</th>
                                                            <th>Comments</th>
                                                            <th>Visits</th>
                                                            <th>Category</th>
                                                            <th>Author</th>
                                                            <th>Created At</th>
                                                            <th>#</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>

                                                        @if (count($articles) > 0)
                                                                @foreach ($articles as $article)
                                                        <tr>
                                                            <th scope="row">{{ $loop->iteration }}</th>
                                                            <td>
                                                                <div class="media-body">
                                                                    <h6 class="d-inline-block">{{ $article->title }}</h6>
                                                                    <p class="m-b-0 text-muted">{{ substr(strip_tags($article->content), 0, 50) }}...</p>
                                                                </div>
                                                            </td>
                                                            <td><a href="{{ route('comments.article_comments', ['id'=>$article->id]) }}">{{ $article->comments()->count() }}</a></td>
                                                            <td>{{ $article->views }}</td>
                                                        <td><a href="{{ route('categories.showArticlesByCategory', ['id'=>$article->category_id]) }}">{{ $article->category->category_name }}</a></td>
                                                            <td>{{ $article->author }}</td>
                                                            <td><h6 class="text-muted">{{ date('d.m.Y', strtotime($article->created_at)) }}</h6></td>
                                                            <td>
                                                                <a href="{{ route('articles.show', ['article'=>$article->id ]) }}" target="_blank"><i class="fas fa-eye f-20 text-c-blue"></i></a> &nbsp; &nbsp;
                                                                <a href="{{ route('articles.edit', ['article'=>$article->id ]) }}"><i class="fas fa-pencil-alt f-20 text-c-yellow"></i></a> &nbsp; &nbsp;
                                                                <a onclick="event.preventDefault(); document.getElementById('article-delete-{{ $article->id }}').submit();"href="{{ route('articles.destroy', ['article'=>$article->id ]) }}"><i class="fas fa-times f-20 text-c-red"></i></a>
                                                                <form action="{{ route('articles.destroy', ['article'=>$article->id ]) }}" method="POST" id="article-delete-{{ $article->id }}">
                                                                    @csrf
                                                                    @method('DELETE')
                                                                </form>
                                                            </td>
                                                        </tr>
                                                                @endforeach
                                                                 
                                                            @else
                                                                <tr>
                                                                    <td colspan="8">There is no any article</td>
                                                                </tr>
                                                            @endif
                                                        
                                                        
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- [ Main Content ] end -->

    @include('shared.scripts')

</body>

</html>